// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLVL_Binh.Database;

#nullable disable

namespace QLVL_Binh.Migrations
{
    [DbContext(typeof(QLVL_BinhContext))]
    [Migration("20240111030158_add_cacytcohai_mayt")]
    partial class add_cacytcohai_mayt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLVL_Binh.Models.Systems.PhienGiaoDichVL.phiengiaodichvl", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("huyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("magd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("nguoilaodong")
                        .HasColumnType("int");

                    b.Property<string>("trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("xa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("phiengiaodichvl");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.PhienGiaoDichVL.phiengiaodichvl_ct", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("magd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noidung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("soluong")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("user")
                        .HasColumnType("int");

                    b.Property<string>("vitri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("phiengiaodichvl_ct");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.Users", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short>("Public")
                        .HasColumnType("smallint");

                    b.Property<string>("capdo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("category")
                        .HasColumnType("smallint");

                    b.Property<bool>("chucnangkhac")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("hethong")
                        .HasColumnType("bit");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("level")
                        .HasColumnType("smallint");

                    b.Property<string>("madv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("madvbc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mahuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manhomchucnang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("matinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maxa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("nhaplieu")
                        .HasColumnType("bit");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("phanloaitk")
                        .HasColumnType("int");

                    b.Property<string>("remember_token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sadmin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("solandn")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<bool>("tonghop")
                        .HasColumnType("bit");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.cacytcohai", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("mayt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phanloai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenyeuto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("cacytcohai");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.capbac", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("madm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tendm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("capbac");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.chanthuong", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<int?>("capdo")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("magoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenchanthuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("chanthuong");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.chucnangs", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<int?>("capdo")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("machucnang_goc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("parent")
                        .HasColumnType("int");

                    b.Property<string>("tencn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("chucnangs");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.company", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<int>("Public")
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("dkkd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("huyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("khucn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("khuvuc")
                        .HasColumnType("int");

                    b.Property<string>("loaihinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("madv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("masodn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nganhnghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quymo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remember_token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sld")
                        .HasColumnType("int");

                    b.Property<string>("tinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("user")
                        .HasColumnType("int");

                    b.Property<string>("website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("xa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("company");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.dangkydv", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("dichvu")
                        .HasColumnType("int");

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("user")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("dangkydv");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.dangkytimviec", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("cccd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chucvu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chungchinn1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chungchinn2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("dantoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("datsotuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gioitinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hinhthuclv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hotroan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("khanangcongtac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kinhnghiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kydieutra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kynangmem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("linhvuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loaihdld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loaihinhkt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loaithk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loaithvp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("luong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("madkkd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maphien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mucdichlv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ngaysinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ngoaingu1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ngoaingu2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nguoikhuyettat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nhanduocviec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phiengd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phucloi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tamtru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tencongviec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tendn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thoidiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thuongtru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tinhockhac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trinhdocmkt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trinhdogiaoduc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("xeploainn1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("xeploainn2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("dangkytimviec");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.danhmuchanhchinh", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<short>("Public")
                        .HasColumnType("smallint");

                    b.Property<string>("capdo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("madb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("madvql")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maquocgia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("parent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("danhmuchanhchinh");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.danhsach", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("donvinhap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("huyen")
                        .HasColumnType("int");

                    b.Property<string>("kydieutra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("loi_cccd")
                        .HasColumnType("int");

                    b.Property<int>("loi_hoten")
                        .HasColumnType("int");

                    b.Property<int>("loi_loai2")
                        .HasColumnType("int");

                    b.Property<int>("loi_loai3")
                        .HasColumnType("int");

                    b.Property<int>("loi_loai4")
                        .HasColumnType("int");

                    b.Property<int>("loi_ngaysinh")
                        .HasColumnType("int");

                    b.Property<int>("soho")
                        .HasColumnType("int");

                    b.Property<int>("soluong")
                        .HasColumnType("int");

                    b.Property<int>("tinh")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("xa")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("danhsach");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.danhsachloi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("bdbhxh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("bddochai")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("bdhopdong")
                        .HasColumnType("datetime2");

                    b.Property<string>("chucvu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cmnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("company")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("dantoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("fromttdvvl")
                        .HasColumnType("smallint");

                    b.Property<string>("ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gioitinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("huyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ktbhxh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ktdochai")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("kthopdong")
                        .HasColumnType("datetime2");

                    b.Property<string>("linhvucdaotao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loaihdld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("luong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("luongbhxh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("nghenghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pcbosung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pcchucvu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pcluong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pcthamnien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pcthamniennghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sobaohiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("state")
                        .HasColumnType("smallint");

                    b.Property<string>("tinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trinhdocmkt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trinhdogiaoduc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("vitri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("xa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("danhsachloi");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.dichvu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("state")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("dichvu");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.dmchucvu", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tencv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("dmchucvu");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.dmdoituonguutiens", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("madmdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stt")
                        .HasColumnType("int");

                    b.Property<string>("tendoituong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("dmdoituonguutiens");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.dmdonvi", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("caphanhchinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chucvuky")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("diadanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("madiaban")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("madv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("madvbc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("madvcq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mahuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("matinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maxa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nguoiky")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phanloaitaikhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tendv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tendvhienthi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ttlienhe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("dmdonvi");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.dmhinhthuclamviec", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("stt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tendm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("dmhinhthuclamviec");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.dmloaihieuluchdld", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("madmlhl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stt")
                        .HasColumnType("int");

                    b.Property<string>("tenlhl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("dmloaihieuluchdld");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.dmloaihinhhdkt", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("madmlhkt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stt")
                        .HasColumnType("int");

                    b.Property<string>("tenlhkt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("dmloaihinhhdkt");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.dmloailaodong", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("madmlld")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stt")
                        .HasColumnType("int");

                    b.Property<string>("tenlld")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("dmloailaodong");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.dmmanghetrinhdo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("madmmntd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manghe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stt")
                        .HasColumnType("int");

                    b.Property<string>("tendmmntd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("dmmanghetrinhdo");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.dmnganhnghe", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("madm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("stt")
                        .HasColumnType("int");

                    b.Property<string>("tendm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("dmnganhnghe");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.dmnganhsxkd", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("madmsxkd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stt")
                        .HasColumnType("int");

                    b.Property<string>("tensxkd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("dmnganhsxkd");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.dmtinhtrangthamgiahdkt", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("madmtgkt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stt")
                        .HasColumnType("int");

                    b.Property<string>("tentgkt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("dmtinhtrangthamgiahdkt");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.dmtinhtrangthamgiahdktct", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("madmtgktct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manhom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stt")
                        .HasColumnType("int");

                    b.Property<string>("tentgktct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("dmtinhtrangthamgiahdktct");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.dmtinhtrangthamgiahdktct2", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("madmtgktct2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manhom2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stt")
                        .HasColumnType("int");

                    b.Property<string>("tentgktct2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("dmtinhtrangthamgiahdktct2");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.dmtrinhdogdpt", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("madmgdpt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tengdpt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("dmtrinhdogdpt");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.dmtrinhdokythuat", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("madmtdkt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stt")
                        .HasColumnType("int");

                    b.Property<string>("tentdkt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("dmtrinhdokythuat");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.donvihanhchinhsunghiep", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<int?>("capdo")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("magoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenhanhchinhsunghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("donvihanhchinhsunghiep");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.donvinhanthongbao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("madv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mahopthu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("donvinhanthongbao");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.dsnhomtaikhoan", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manhomchucnang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stt")
                        .HasColumnType("int");

                    b.Property<string>("tennhomchucnang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("dsnhomtaikhoan");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.dsnhomtaikhoan_phanquyen", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("DeleteRecordTrash")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("danhsach")
                        .HasColumnType("bit");

                    b.Property<string>("ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("hoanthanh")
                        .HasColumnType("bit");

                    b.Property<string>("machucnang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manhomchucnang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("phanquyen")
                        .HasColumnType("bit");

                    b.Property<bool>("thaydoi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("dsnhomtaikhoan_phanquyen");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.dstaikhoan_phanquyen", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("danhsach")
                        .HasColumnType("bit");

                    b.Property<string>("ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("hoanthanh")
                        .HasColumnType("bit");

                    b.Property<string>("machucnang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("phanquyen")
                        .HasColumnType("bit");

                    b.Property<string>("tendangnhap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("thaydoi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("dstaikhoan_phanquyen");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.dsthatnghiep", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("bhxh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cccd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gioitinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("huyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kydieutra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ngaysinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nghecongviec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nghenghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nguyennhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trinhdocmkt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("xa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("dsthatnghiep");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.hopthu", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("dvnhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("file")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("loaithu")
                        .HasColumnType("int");

                    b.Property<string>("lydo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("madv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mahuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("matinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noidung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thoigiangui")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tieude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("hopthu");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.kybaocao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("cqtiepnhan_h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cqtiepnhan_x")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("kydieutra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lydo_h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lydo_x")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("madv_h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("madv_t")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("madv_x")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noidung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thoidiem_h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thoidiem_t")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thoidiem_x")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangthai_h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangthai_t")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangthai_x")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("kybaocao");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.messages", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("cqtiepnhan_h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cqtiepnhan_x")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("kydieutra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lydo_h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lydo_x")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("madv_h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("madv_t")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("madv_x")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noidung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thoidiem_h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thoidiem_t")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thoidiem_x")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangthai_h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangthai_t")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangthai_x")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.nghecongviec", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("stt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tendm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("nghecongviec");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.nguoilaodong", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("bdbhxh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("bddochai")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("bdhopdong")
                        .HasColumnType("datetime2");

                    b.Property<string>("ccnd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chucvu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("company")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("dantoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("fromttdvvl")
                        .HasColumnType("smallint");

                    b.Property<string>("ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gioitinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("huyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ktbhxh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ktdochai")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("kthopdong")
                        .HasColumnType("datetime2");

                    b.Property<string>("linhvucdaotao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loaihdld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("luong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("luongbhxh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("nghenghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pcbosung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pcchucvu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pcluong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pcthamnien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pcthamniennghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sobaohiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("state")
                        .HasColumnType("smallint");

                    b.Property<string>("tinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trinhdocmkt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trinhdogiaoduc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("vitri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("xa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("nguoilaodong");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.nguyennhanthatnghiep", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("stt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tennn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("nguyennhanthatnghiep");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.nhankhau", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("bhxh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cccd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chuyenmonkythuat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chuyennganh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("congvieccuthe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("danhsach_id")
                        .HasColumnType("int");

                    b.Property<string>("dantoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("diachinoilamviec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("doituongtimvieclam")
                        .HasColumnType("int");

                    b.Property<string>("gioitinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hdld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("khongthamgiahdkt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("khuvuc")
                        .HasColumnType("int");

                    b.Property<string>("kydieutra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("loaibiendong")
                        .HasColumnType("int");

                    b.Property<string>("loaihinhnoilamviec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lydo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("madv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maloailoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maloi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mqh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nganhnghemongmuon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nganhnghemuonhoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ngaysinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nguoicovieclam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noilamviec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("soluongtrung")
                        .HasColumnType("int");

                    b.Property<string>("thamgiabhxh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thatnghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thitruonglamviec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thoigianthatnghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thuongtru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tinhtranghdkt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trinhdochuyenmonmuonhoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trinhdogiaoduc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("truongbiendong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("uutien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("vieclammongmuon")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("nhankhau");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.param", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("param");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.paramtype", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("paramtype");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.participants", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("last_read")
                        .HasColumnType("datetime2");

                    b.Property<long>("thread_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("participants");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.password_resets", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("password_resets");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.report", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("datatable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iprequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kydieutra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("result")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("time")
                        .HasColumnType("datetime2");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("user")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("report");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.threads", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("attach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("threads");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.tonghopcunglaodong", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("capdo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("hocnghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kydieutra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ldcovieclam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ldkhongthamgia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ldthatnghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ldtren15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("madv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nongthon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nuocngoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tendv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thanhthi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trongnuoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("tonghopcunglaodong");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.tuyendung", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("chucvutd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contacttype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<short?>("datuyen")
                        .HasColumnType("smallint");

                    b.Property<short?>("datuyentutt")
                        .HasColumnType("smallint");

                    b.Property<string>("emailtd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noidung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phonetd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("state")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("thoihan")
                        .HasColumnType("datetime2");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("user")
                        .HasColumnType("int");

                    b.Property<string>("yeucau")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tuyendung");
                });

            modelBuilder.Entity("QLVL_Binh.Models.Systems.vitrituyendung", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<short?>("bacnge")
                        .HasColumnType("smallint");

                    b.Property<string>("capbac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chucvu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chungchinn1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chungchinn2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chuyennganh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("diadiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dungtay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dungvadilai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hinhthuclv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hotroan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idtuyendung")
                        .HasColumnType("int");

                    b.Property<string>("kynangmem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loaihopdong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loaithk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loaithvp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mucdichlv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mucluong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nghenoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ngoaingu1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ngoaingu2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noilamviec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phucloi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("soluong")
                        .HasColumnType("smallint");

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tdcmkt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tdgd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thaotactay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thiluc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tinhockhac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trinhdonghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trongluongnang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("uutien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("xeploainn1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("xeploainn2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yeucaukn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yeucauthem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("vitrituyendung");
                });
#pragma warning restore 612, 618
        }
    }
}
